# Generated by Django 5.2.8 on 2025-12-06 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=100, unique=True)),
                ('kategori', models.CharField(choices=[('MOTOR', 'Sepeda Motor'), ('MOBIL', 'Mobil'), ('JEEP', 'Jeep'), ('TRUK', 'Truk'), ('BUS', 'Bus'), ('LAINNYA', 'Lainnya')], default='MOTOR', max_length=50)),
            ],
            options={
                'verbose_name': 'Jenis Kendaraan',
                'verbose_name_plural': 'Jenis Kendaraan',
                'db_table': 'jenis_kendaraan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MerekKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Merek Kendaraan',
                'verbose_name_plural': 'Merek Kendaraan',
                'db_table': 'merek_kendaraan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'db_table': 'kecamatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=100)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelurahan', to='crud.kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan',
                'verbose_name_plural': 'Kelurahan',
                'db_table': 'kelurahan',
                'ordering': ['nama'],
                'unique_together': {('kecamatan', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='TypeKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_kendaraan', to='crud.merekkendaraan')),
                ('nama', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Type Kendaraan',
                'verbose_name_plural': 'Type Kendaraan',
                'db_table': 'type_kendaraan',
                'ordering': ['merek', 'nama'],
                'unique_together': {('merek', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='WajibPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelurahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wajib_pajak', to='crud.kelurahan')),
                ('no_ktp', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('nama', models.CharField(db_index=True, max_length=200)),
                ('alamat', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wajib Pajak',
                'verbose_name_plural': 'Wajib Pajak',
                'db_table': 'wajib_pajak',
            },
        ),
        migrations.CreateModel(
            name='KendaraanBermotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kendaraan', to='crud.jeniskendaraan')),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kendaraan', to='crud.merekkendaraan')),
                ('type_kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kendaraan', to='crud.typekendaraan')),
                ('wajib_pajak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kendaraan', to='crud.wajibpajak')),
                ('no_polisi', models.CharField(db_index=True, max_length=20, unique=True)),
                ('no_rangka', models.CharField(db_index=True, max_length=50, unique=True)),
                ('no_mesin', models.CharField(db_index=True, max_length=100)),
                ('tahun_buat', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('jml_cc', models.IntegerField(verbose_name='Kapasitas Mesin (CC)')),
                ('bbm', models.CharField(choices=[('BENSIN', 'Bensin'), ('SOLAR', 'Solar'), ('LISTRIK', 'Listrik'), ('HYBRID', 'Hybrid')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kendaraan Bermotor',
                'verbose_name_plural': 'Kendaraan Bermotor',
                'db_table': 'kendaraan_bermotor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPajakKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kendaraan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_pajak', to='crud.kendaraanbermotor')),
                ('njkb_saat_ini', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='NJKB Saat Ini')),
                ('bobot_saat_ini', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('dp_pkb_saat_ini', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dasar Pengenaan PKB')),
                ('tarif_pkb_saat_ini', models.DecimalField(decimal_places=2, default=0, help_text='Tarif PKB dalam persen', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Pajak Kendaraan',
                'verbose_name_plural': 'Data Pajak Kendaraan',
                'db_table': 'data_pajak_kendaraan',
            },
        ),
        migrations.CreateModel(
            name='HasilPrediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.jeniskendaraan')),
                ('tahun_prediksi', models.IntegerField(db_index=True)),
                ('bulan_prediksi', models.IntegerField(db_index=True)),
                ('metode', models.CharField(choices=[('SES', 'Simple Exponential Smoothing'), ('DES', 'Double Exponential Smoothing (Holt)'), ('TES', 'Triple Exponential Smoothing (Holt-Winters)')], max_length=10)),
                ('nilai_prediksi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('alpha', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('seasonal_periods', models.IntegerField(blank=True, default=12, null=True)),
                ('mape', models.DecimalField(blank=True, decimal_places=4, help_text='Mean Absolute Percentage Error', max_digits=10, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Error', max_digits=20, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, help_text='Root Mean Squared Error', max_digits=20, null=True)),
                ('nilai_aktual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tanggal_prediksi', models.DateTimeField(auto_now_add=True)),
                ('data_training_dari', models.DateField()),
                ('data_training_sampai', models.DateField()),
                ('jumlah_data_training', models.IntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hasil Prediksi',
                'verbose_name_plural': 'Hasil Prediksi',
                'db_table': 'hasil_prediksi',
                'ordering': ['-tahun_prediksi', '-bulan_prediksi'],
                'indexes': [models.Index(fields=['tahun_prediksi', 'bulan_prediksi'], name='hasil_predi_tahun_p_347cd5_idx'), models.Index(fields=['metode'], name='hasil_predi_metode_f15afd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgregatPendapatanBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.jeniskendaraan')),
                ('tahun', models.IntegerField(db_index=True)),
                ('bulan', models.IntegerField(db_index=True)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pokok_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_denda_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_swdkllj', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_bbnkb', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_opsen', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jumlah_transaksi', models.IntegerField(default=0)),
                ('jumlah_kendaraan', models.IntegerField(default=0)),
                ('tanggal_agregasi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agregat Pendapatan Bulanan',
                'verbose_name_plural': 'Agregat Pendapatan Bulanan',
                'db_table': 'agregat_pendapatan_bulanan',
                'ordering': ['-tahun', '-bulan'],
                'indexes': [models.Index(fields=['tahun', 'bulan'], name='agregat_pen_tahun_863aae_idx'), models.Index(fields=['total_pendapatan'], name='agregat_pen_total_p_83397b_idx')],
                'unique_together': {('tahun', 'bulan', 'jenis_kendaraan')},
            },
        ),
        migrations.CreateModel(
            name='TransaksiPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='crud.kendaraanbermotor')),
                ('tahun', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000)])),
                ('bulan', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tgl_pajak', models.DateField(blank=True, db_index=True, null=True)),
                ('jml_tahun_bayar', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('jml_bulan_bayar', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tgl_bayar', models.DateField(blank=True, db_index=True, null=True)),
                ('pokok_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('denda_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tunggakan_pokok_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tunggakan_denda_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opsen_pokok_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opsen_denda_pkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pokok_swdkllj', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('denda_swdkllj', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tunggakan_pokok_swdkllj', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tunggakan_denda_swdkllj', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pokok_bbnkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('denda_bbnkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bbnkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opsen_pokok_bbnkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opsen_denda_bbnkb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bayar', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaksi Pajak',
                'verbose_name_plural': 'Transaksi Pajak',
                'db_table': 'transaksi_pajak',
                'ordering': ['-tahun', '-bulan'],
                'indexes': [models.Index(fields=['tahun', 'bulan'], name='transaksi_p_tahun_349379_idx'), models.Index(fields=['tgl_pajak'], name='transaksi_p_tgl_paj_90362d_idx'), models.Index(fields=['tgl_bayar'], name='transaksi_p_tgl_bay_32c554_idx'), models.Index(fields=['kendaraan', 'tahun', 'bulan'], name='transaksi_p_kendara_b92c9c_idx'), models.Index(fields=['total_bayar'], name='transaksi_p_total_b_f0a01a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wajibpajak',
            index=models.Index(fields=['no_ktp'], name='wajib_pajak_no_ktp_aee218_idx'),
        ),
        migrations.AddIndex(
            model_name='wajibpajak',
            index=models.Index(fields=['nama'], name='wajib_pajak_nama_8cc8da_idx'),
        ),
        migrations.AddIndex(
            model_name='kendaraanbermotor',
            index=models.Index(fields=['no_polisi'], name='kendaraan_b_no_poli_5d5c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='kendaraanbermotor',
            index=models.Index(fields=['no_rangka'], name='kendaraan_b_no_rang_865dea_idx'),
        ),
        migrations.AddIndex(
            model_name='kendaraanbermotor',
            index=models.Index(fields=['wajib_pajak', 'tahun_buat'], name='kendaraan_b_wajib_p_6c2cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='kendaraanbermotor',
            index=models.Index(fields=['jenis', 'merek'], name='kendaraan_b_jenis_i_283cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='kendaraanbermotor',
            index=models.Index(fields=['tahun_buat'], name='kendaraan_b_tahun_b_4dfd38_idx'),
        ),
    ]
