# Generated by Django 5.2.8 on 2026-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_kendaraanbermotor_merek'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kendaraanbermotor',
            new_name='kendaraan_b_jenis_i_bbd486_idx',
            old_name='kendaraan_b_jenis_i_283cd9_idx',
        ),
        migrations.AlterField(
            model_name='hasilprediksi',
            name='metode',
            field=models.CharField(choices=[('SES', 'Simple Exponential Smoothing'), ('DES', 'Double Exponential Smoothing (Holt)'), ('TES', 'Triple Exponential Smoothing (Holt-Winters)'), ('HYBRID_CONSERVATIVE', 'Hybrid - Conservative Scenario'), ('HYBRID_BASE', 'Hybrid - Base Scenario'), ('HYBRID_MODERATE', 'Hybrid - Moderate Scenario'), ('HYBRID_OPTIMISTIC', 'Hybrid - Optimistic Scenario')], max_length=20),
        ),
    ]
