# Generated by Django 5.2.8 on 2026-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pimpinan', 'Kepala UPPD/SAMSAT'), ('manager', 'Manager'), ('user', 'User'), ('staff', 'Staff')], default='user', help_text='Role pengguna dalam sistem', max_length=20),
        ),
    ]
